### ISSUE TITLE
how to run this project?

### ISSUE THREAD

**Issue by julioc98** [Adyen/adyen-report-merger#5]
how to run this project?

**Comment by julioc98** [comment]
R.: `java -jar adyen-report-merger.jar`

**Comment by zmandell** [comment]
I've tried the above to run the project but am receiving an error. In fact, I don't think the file in the command exists in this version of the project. How should the project be run?

**Comment by AlicjaCiunczyk** [comment]
Hi @zmandell, the adyen-report-merger.jar is available in the Releases part -> https://github.com/Adyen/adyen-report-merger/releases/tag/1.4.0.

**Comment by daanvinken** [comment]
Hi all,

I've updated the [README](https://github.com/Adyen/adyen-report-merger/blob/develop/README.md) with a bit more context on how to run this application.

Please note that this repository is deprecated and not supported by Adyen anymore.
We provide additional functionalities to merge reports in our Customer Area. You can do this by going to **Reports > Select your report type > click _Generate reports_ > Select _bulk_ for multiple dates.**

I will be closing this issue. 
If you have any more questions on reports in the Customer Area, you can contact our support team.
