### ISSUE TITLE
Java issue

### ISSUE THREAD

**Issue by thomasfaron** [Adyen/adyen-report-merger#9]
**Describe the bug**
Error message when trying to download the tool. Merchant technical teams investigated but do not see the issue. Other workers in that company do use the tool.
Difference between two users is one using Windows 10 the other windows 7
![image001](https://user-images.githubusercontent.com/86005954/122233962-be7d7a80-cebc-11eb-803d-06f6827a2b09.png)
Any idea what can be the issue?

Thanks,

**Comment by daanvinken** [comment]
Hi @thomasfaron!

As we took this discussion offline I'm hereby closing this issue. 
If you have any questions feel free to contact me directly.
